name: CI

on:
    push:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt'] 
    pull_request:
        branches: main
        paths: ['**.cpp', '**.h', '**CMakeLists.txt']

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Java
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle' # See 'Supported distributions' for available options
                java-version: '17'
            
            - name: Clone Minecraft_Tools
              run: git clone https://github.com/nhatdongdang/Minecraft_Tools

            - name: Start Spigot Server
              working-directory: ./Minecraft_Tools/server
              run: nohup java -Xms512M -Xmx1024M -jar -DIReallyKnowWhatIAmDoingISwear spigot-1.19.4.jar nogui -o true & sleep 45

            - name: Join Spigot Server
              working-directory: ./Minecraft_Tools/MinecraftClient
              run: ./MinecraftClient &

            - name: Checkout mcpp
              uses: actions/checkout@v4

            - name: Build file
              run: cmake -Bbuild

            - name: Run test suite
              working-directory: ./build
              run: make test_suite && ctest -R full